CREATE OR REPLACE FUNCTION bid_check() RETURNS trigger AS $bid_check$
    DECLARE NO_BIDS INTEGER;
    DECLARE NO_VACANCY INTEGER;
    BEGIN
	IF NEW.accepted = 't' THEN
		--FIND NO OF VACANCY
		SELECT C.VACANCY INTO NO_VACANCY FROM CAR_RIDES C
		WHERE C.PLATE_NUMBER = NEW.PLATE_NUMBER 
		AND C.START_TIME = NEW.START_TIME;
		--FIND NO OF ACCEPTED BIDS
		SELECT COUNT(*) INTO NO_BIDS FROM BIDS B
		WHERE  B.PLATE_NUMBER = NEW.PLATE_NUMBER 
		AND B.START_TIME = NEW.START_TIME AND B.ACCEPTED = TRUE;
		IF NO_BIDS < NO_VACANCY THEN
			RETURN NEW;
		ELSE
			RAISE NOTICE 'No. of accepted bids cannot be more than no. of vacancy';
		END IF;
	ELSE
		RETURN NEW;
        END IF;
	RETURN NULL;
    END; $bid_check$ LANGUAGE plpgsql;

CREATE TRIGGER bid_trigger BEFORE UPDATE ON bids
    FOR EACH ROW EXECUTE PROCEDURE bid_check();
